/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class FrameImportar_palabras extends javax.swing.JPanel {

    /**
     * Creates new form Importar_palabras
     */

    public FrameImportar_palabras() {
        initComponents();
        validarRuta();
        
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtxtRuta = new javax.swing.JTextField();
        jbtnVolver = new javax.swing.JButton();
        jbtnImportar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Ruta del archivo:");

        jtxtRuta.setText("jTextField1");

        jbtnVolver.setText("jButton1");

        jbtnImportar.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jtxtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jbtnVolver)
                        .addGap(133, 133, 133)
                        .addComponent(jbtnImportar)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnVolver)
                    .addComponent(jbtnImportar))
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents
public String getRutaArchivo() {
    return jtxtRuta.getText();
}
public boolean validarRuta() {
    if (jtxtRuta.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar una ruta de archivo.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return false;
    }
    return true;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton jbtnImportar;
    public javax.swing.JButton jbtnVolver;
    public javax.swing.JTextField jtxtRuta;
    // End of variables declaration//GEN-END:variables
}
