/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.Controlador;
import controladores.ControladorImporte;
import controladores.ControladorJuego;
import controladores.ControladorJugadores;
import controladores.ControladorPalabras;
import controladores.Controlador_Categorias;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Categoria;
import modelo.ImportarPalabras;
import modelo.ModeloJuego;

/**
 *
 * @author HP
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form ventana_juego
     */
    controladores.Controlador controlador;
    private JPanel paneles;

    ImportarPalabras modeloImportar = new ImportarPalabras();
    FrameImportar_palabras vistaImportar = new FrameImportar_palabras();
    ControladorImporte controladorImporte = new ControladorImporte(modeloImportar, vistaImportar);

    public menu() {
        initComponents();

        // Crear un contenedor para centrar los paneles
        JPanel contenedorCentrado = new JPanel(new GridBagLayout());

        // Crear el panel con CardLayout para manejar las vistas
        paneles = new JPanel(new CardLayout());
        paneles.add(jPnlMenu, "menu"); // Panel principal del menú
        paneles.add(vistaImportar, "importar");
        paneles.add(new FrmAnadir_categorias(), "categorias");
        paneles.add(new FrmAnadirJugadores(), "jugadores");
        paneles.add(new FrameAnadir_palabras(), "palabras");
        paneles.add(new FrmJuego(), "juego");

        // Agregar el panel con CardLayout al contenedor centrado
        contenedorCentrado.add(paneles, new GridBagConstraints());

        // Configurar el panel exterior
        jPanel3.setLayout(new BorderLayout());
        jPanel3.add(contenedorCentrado, BorderLayout.CENTER);

        // Mostrar el panel inicial
        mostrarPanel("menu");
        this.setSize(800, 600); // Define el tamaño de la ventana (puedes ajustarlo)
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setVisible(true); // Mostrar la ventana
    }

    private void mostrarPanel(String panel) {
        CardLayout layout = (CardLayout) paneles.getLayout();
        layout.show(paneles, panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelExterior = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPnlMenu = new javax.swing.JPanel();
        jbtnImport = new javax.swing.JButton();
        jBtnCategorias = new javax.swing.JButton();
        jBtnPalabras = new javax.swing.JButton();
        jBtnJugadores = new javax.swing.JButton();
        jBtnJuego = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanelExterior.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 8)); // NOI18N
        jLabel1.setText("FIESTRA");

        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)))
        );

        jPnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPnlMenu.setForeground(new java.awt.Color(255, 255, 255));

        jbtnImport.setText("Importar palabras");
        jbtnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImportActionPerformed(evt);
            }
        });

        jBtnCategorias.setText("Añadir categoria");
        jBtnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCategoriasActionPerformed(evt);
            }
        });

        jBtnPalabras.setText("Añadir palabras");
        jBtnPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPalabrasActionPerformed(evt);
            }
        });

        jBtnJugadores.setText("Registrar jugadores");
        jBtnJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnJugadoresActionPerformed(evt);
            }
        });

        jBtnJuego.setText("Iniciar Juego");
        jBtnJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnJuegoActionPerformed(evt);
            }
        });

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlMenuLayout = new javax.swing.GroupLayout(jPnlMenu);
        jPnlMenu.setLayout(jPnlMenuLayout);
        jPnlMenuLayout.setHorizontalGroup(
            jPnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMenuLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addGroup(jPnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnPalabras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jBtnJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jPnlMenuLayout.setVerticalGroup(
            jPnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMenuLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jbtnImport)
                .addGap(18, 18, 18)
                .addComponent(jBtnCategorias)
                .addGap(18, 18, 18)
                .addComponent(jBtnPalabras)
                .addGap(18, 18, 18)
                .addComponent(jBtnJugadores)
                .addGap(18, 18, 18)
                .addComponent(jBtnJuego)
                .addGap(18, 18, 18)
                .addComponent(jBtnSalir)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpanelExteriorLayout = new javax.swing.GroupLayout(jpanelExterior);
        jpanelExterior.setLayout(jpanelExteriorLayout);
        jpanelExteriorLayout.setHorizontalGroup(
            jpanelExteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelExteriorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpanelExteriorLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jpanelExteriorLayout.setVerticalGroup(
            jpanelExteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelExteriorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelExterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelExterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if (true) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jBtnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCategoriasActionPerformed

        // Obtén la referencia existente en el panel
        FrmAnadir_categorias vistaCategorias = (FrmAnadir_categorias) paneles.getComponent(2); // Índice correspondiente al panel de categorías
        new Controlador_Categorias(vistaCategorias, modeloImportar);
        mostrarPanel("categorias");


    }//GEN-LAST:event_jBtnCategoriasActionPerformed

    private void jbtnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImportActionPerformed
        // Utiliza la instancia existente en el panel
        FrameImportar_palabras vistaImportar = (FrameImportar_palabras) paneles.getComponent(1); // Índice correspondiente al panel "importar"
        new ControladorImporte(modeloImportar, vistaImportar);
        mostrarPanel("importar");

    }//GEN-LAST:event_jbtnImportActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "está seguro de salir?") == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPalabrasActionPerformed
        // Utiliza la instancia existente en el panel
        FrameAnadir_palabras vistaPalabras = (FrameAnadir_palabras) paneles.getComponent(4); // Índice correspondiente al panel "palabras"
        new ControladorPalabras(vistaPalabras, modeloImportar);
        mostrarPanel("palabras");
    }//GEN-LAST:event_jBtnPalabrasActionPerformed

    private void jBtnJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnJugadoresActionPerformed
        FrmAnadirJugadores vistaJugador = (FrmAnadirJugadores) paneles.getComponent(3);
        new ControladorJugadores(vistaJugador);
        mostrarPanel("jugadores");
    }//GEN-LAST:event_jBtnJugadoresActionPerformed

    private void jBtnJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnJuegoActionPerformed
        FrmJuego vistajuego = (FrmJuego) paneles.getComponent(5);
        ModeloJuego modeloJuego = new ModeloJuego(modeloImportar.getCategorias()); // Asegúrate de usar siempre la misma instancia.
        new ControladorJuego(modeloJuego, vistajuego);
        mostrarPanel("juego");
        

    }//GEN-LAST:event_jBtnJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCategorias;
    private javax.swing.JButton jBtnJuego;
    private javax.swing.JButton jBtnJugadores;
    private javax.swing.JButton jBtnPalabras;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPnlMenu;
    private javax.swing.JButton jbtnImport;
    private javax.swing.JPanel jpanelExterior;
    // End of variables declaration//GEN-END:variables
}
